name: Build test

on:
  workflow_dispatch:        # can be triggered manually
  pull_request:             # and for PRs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Build
        run: |
          npm ci
          npm run build
          # creates a .nojekyll file in the out directory to tell GitHub Pages not to treat the site as a Jekyll project.
          touch build/.nojekyll
